"use strict";
const fs=require('fs'),assert=require('node:assert/strict');
const {chromium}=require('../api-fable-review-20260907/node_modules/playwright');
(async()=>{const html=fs.readFileSync('index.html','utf8');const start=html.indexOf('async function psLiveTurnPriority(){'),end=html.indexOf('// ══ APPLICATION REVIEW',start);assert(start>=0&&end>start);const browser=await chromium.launch({headless:true,executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe'});try{const page=await browser.newPage({viewport:{width:390,height:844}});await page.setContent('<main id="psTurnPriBody"></main>');await page.addStyleTag({content:[...html.matchAll(/<style[^>]*>([\s\S]*?)<\/style>/gi)].map(m=>m[1]).join('\n')});await page.evaluate(()=>{window.esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));window.__psLive={loadResource:async()=>({data:window.payload})};});await page.addScriptTag({content:html.slice(start,end)});
const row={unit_label:'101',demand_tier_key:'committed_start',deadline_known:true,commitment_start_date:'2026-10-10',rentable_space_count:3,reason:'Committed move-in starts 2026-10-10.',contributing_commitments:[{space_id:'bed-b',space_label:'Bed B',lease_id:'lease-b',state:'locked',start_date:'2026-10-10'},{space_id:'bed-c',space_label:'Bed <C>',lease_id:'lease-c',state:'pending',start_date:null}]};
await page.evaluate(async r=>{window.payload={turns:[r]};await psLiveTurnPriority();},row);
assert.equal(await page.locator('#psTurnPriBody').getAttribute('data-ps-state'),'data');assert.equal(await page.locator('#psTurnPriBody details').count(),1,'By-bed contributors must be inspectable');await page.locator('summary').click();let text=await page.locator('#psTurnPriBody').innerText();assert(text.includes('Bed B'));assert(text.includes('Bed <C>'));assert(text.includes('Start date not recorded'));assert.equal(await page.locator('#psTurnPriBody c').count(),0,'Labels must remain text');
await page.evaluate(async r=>{window.payload={turns:[{...r,demand_tier_key:'conflicted_commitment',deadline_known:false,commitment_start_date:null,reason:'Lease claims conflict; no deadline established.',demand:{move_in_date:'2099-12-31',applicant_name:'Fixture applicant'}}]};await psLiveTurnPriority();},row);text=await page.locator('#psTurnPriBody').innerText();assert(text.includes('CONFLICT'));assert(!text.includes('2099'));assert(!text.includes('Fixture applicant'));
await page.evaluate(async()=>{window.payload={turns:[]};await psLiveTurnPriority();});assert.equal(await page.locator('#psTurnPriBody').getAttribute('data-ps-state'),'empty');await page.evaluate(async()=>{window.payload={};await psLiveTurnPriority();});assert.equal(await page.locator('#psTurnPriBody').getAttribute('data-ps-state'),'unavailable');console.log('PASS live maintenance contributors, exact labels, unknown dates, conflict without fixture fallback, empty/failure');}finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1)});
